

spring:
  application:
    name: exam
  datasource:
    url: jdbc:sqlite:exam.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update